Repository TaQuangKhoi/Bao-Cao-Web-3, pull requests merged in 2023-11, with the labels that each got.

#41 Functions Sign In and Logout
  Pipfile
  Pipfile.lock
  caythue/settings.py
  caythue/urls.py
  signin/forms.py
  signin/templates/form_snippet.jinja
  signin/templates/signin.jinja
  signin/templates/signin_base.jinja
  signin/views.py
  ui/templates/base.jinja
  ui/templates/components.jinja
  ui/templates/dashboard.jinja
  ui/urls.py
  ui/views.py
Labels: enhancement

#48 Edit uprank và tạo app dashboard
  caythue/settings.py
  caythue/urls.py
  dashboard/__init__.py
  dashboard/admin.py
  dashboard/apps.py
  dashboard/migrations/__init__.py
  dashboard/models.py
  dashboard/templates/dashboard.jinja
  dashboard/tests.py
  dashboard/urls.py
  dashboard/views.py
  ui/static/up_rank/silver-2.png
  ui/urls.py
  ui/views.py
  uprank/templates/up_rank.jinja
Labels: bug, enhancement

#51 Done #36
  caythue/urls.py
  caythue/views.py
  dashboard/urls.py
  dashboard/views.py
Labels: enhancement

#55 Click Cày rank to go to up_rank
  home/templates/home.jinja
Labels: enhancement

#56 Go to page sign-in from home
  home/templates/button-go-to-sign-in.jinja
  home/templates/home.jinja
Labels: enhancement

#58 57 Create app `library_db`
  caythue/settings.py
  library_db/__init__.py
  library_db/admin.py
  library_db/apps.py
  library_db/migrations/0001_initial.py
  library_db/migrations/0002_delete_gametype_delete_server.py
  library_db/migrations/0003_gametype_server.py
  library_db/migrations/__init__.py
  library_db/models.py
  library_db/tests.py
  library_db/views.py
  ui/admin.py
  ui/migrations/0009_alter_request_request_creation_date_and_more.py
  ui/migrations/0010_alter_request_request_creation_date_and_more.py
  ui/migrations/0011_alter_request_request_creation_date_and_more.py
  ui/migrations/0012_alter_request_request_creation_date_and_more.py
  ui/migrations/0013_alter_request_request_creation_date_and_more.py
  ui/migrations/0014_alter_request_request_creation_date_and_more.py
  ui/migrations/0015_delete_gametype_remove_request_current_rank_and_more.py
  ui/models.py
Labels: enhancement

#63 button from signin to home
  signin/templates/signin_base.jinja
Labels: enhancement

#70 Use template files on othe app
  caythue/settings.py
  caythue/templates/caythue/signin_base.jinja
  caythue/urls.py
  signin/templates/signin.jinja
  signin/urls.py
  signin/views.py
  signup/__init__.py
  signup/admin.py
  signup/apps.py
  signup/migrations/__init__.py
  signup/models.py
  signup/templates/signup.jinja
  signup/tests.py
  signup/urls.py
  signup/views.py
Labels: enhancement

#66 Make function Register
  signup/__init__.py
  signup/admin.py
  signup/apps.py
  signup/migrations/__init__.py
  signup/models.py
  signup/tests.py
  signup/views.py
Labels: enhancement

#68 File base for app dashboard
  dashboard/static/base/OneSignalSDK.js.download
  dashboard/static/base/ckeditor.js.download
  dashboard/static/base/default-avatar.webp
  dashboard/static/base/logo-icon.svg
  dashboard/static/base/main.9ddc26dd19fa0a66.js.download
  dashboard/static/base/polyfills.8af294937448abd7.js.download
  dashboard/static/base/runtime.1ea393a517ace7c5.js.download
  dashboard/static/base/samurai-2.webp
  dashboard/static/base/scripts.c3632ebff9948177.js.download
  dashboard/static/base/styles.13124b6b853a8a65.css
  dashboard/static/base/v84a3a4012de94ce1a686ba8c167c359c1696973893317
  dashboard/templates/dashboard.jinja
  dashboard/templates/dashboardbase.jinja
  home/templates/home.jinja
Labels: enhancement

#79 Restore logout function in dashboardbase.jinja
  dashboard/templates/dashboardbase.jinja
Labels: bug

#75 Upload Order List
  dashboard/templates/dashboardbase.jinja
  dashboard/templates/order.jinja
  dashboard/urls.py
  dashboard/views.py
Labels: enhancement

#83 Custom goToSignInButton
  home/templates/button-go-to-sign-in.jinja
  home/templates/home.jinja
Labels: enhancement

#89 86 rebuild logic for sidebar in dashboard
  dashboard/static/dashboard/OneSignalSDK.js.download
  dashboard/static/dashboard/ckeditor.js.download
  dashboard/static/dashboard/default-avatar.webp
  dashboard/static/dashboard/logo-icon.svg
  dashboard/static/dashboard/main.9ddc26dd19fa0a66.js.download
  dashboard/static/dashboard/polyfills.8af294937448abd7.js.download
  dashboard/static/dashboard/private/styles.css
  dashboard/static/dashboard/runtime.1ea393a517ace7c5.js.download
  dashboard/static/dashboard/samurai-2.webp
  dashboard/static/dashboard/scripts.c3632ebff9948177.js.download
  dashboard/static/dashboard/styles.13124b6b853a8a65.css
  dashboard/static/dashboard/v84a3a4012de94ce1a686ba8c167c359c1696973893317
  dashboard/templates/dashboardbase.jinja
  dashboard/templates/sidebar_item.jinja
Labels: enhancement

#91 Done restore table Request
  dashboard/templates/dashboard.jinja
  uprank/admin.py
  uprank/migrations/0002_delete_request.py
  uprank/migrations/0003_initial.py
  uprank/migrations/0004_request_current_rank_alter_request_server.py
  uprank/migrations/0005_request_desired_rank.py
  uprank/migrations/0006_request_created_by.py
  uprank/models.py
Labels: enhancement

#94 74 make logic to create new request in up rank app
  dashboard/templates/dashboardbase.jinja
  dashboard/views.py
  library_db/models.py
  uprank/forms.py
  uprank/migrations/0007_alter_request_current_lp_and_more.py
  uprank/models.py
  uprank/static/uprank/app.js
  uprank/static/uprank/styles.css
  uprank/templates/up_rank.jinja
  uprank/templates/up_rank_base.jinja
  uprank/views.py
Labels: enhancement

#98 97 add logic to generate detail in table request
  uprank/choices.py
  uprank/forms.py
  uprank/migrations/0008_alter_request_lp_gain.py
  uprank/migrations/0009_alter_request_details.py
  uprank/models.py
  uprank/views.py
Labels: enhancement

#99 54 show data of request table in orders of dashboard
  dashboard/static/order/styles.css
  dashboard/templates/dashboardbase.jinja
  dashboard/templates/order.jinja
  dashboard/views.py
  uprank/views.py
Labels: enhancement
